config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :resumes do
    resources :messages
  end

  resources :messages, only: [:index]

  authenticated :user do
    root 'resumes#index', as: :authenticated_root
  end

  root 'home#index'
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :resume

  after_create :send_resume_message_email

  default_scope { order(created_at: :desc) }

  validates :recipient, presence: true
  validates :subject, presence: true
  validates :body, presence: true
  validates_format_of :recipient,:with => Devise::email_regexp

  private
  def send_resume_message_email
    ResumeMessageMailer.resume_message_email(self.recipient, self.resume.user.email, self.subject, self.body, self.resume.document).deliver_now
  end
end

app/models/resume.rb
class Resume < ActiveRecord::Base
  has_attached_file :document

  belongs_to :user
  has_many :messages, dependent: :destroy

  validates :name, presence: true
  validates_attachment :document,
    presence: true,
    content_type: { content_type: ["application/pdf",
                                  "application/msword",
                                  "application/vnd.openxmlformats-officedocument.wordprocessingml.document"] },
    size: { in: 0..1000.kilobytes }

  after_validation :cleanup_paperclip_duplicate_errors

  private
  def cleanup_paperclip_duplicate_errors
    errors.delete(:document)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :resumes, dependent: :destroy
  has_many :messages, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_resume, except: [:index]
  before_action :set_message, only: [:show, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  def index
    @messages = current_user.messages
  end

  def new
    @message = Message.new
  end

  def create
    @message = @resume.messages.new(message_params)
    @message.user_id = current_user.id

    if @message.save
      flash[:notice] = "Your message was successfully sent."
      redirect_to resume_messages_path
    else
      render :new
    end
  end

  def show
  end

  def destroy
    if @message.destroy
      flash[:notice] = "Your message was deleted successfully."
      redirect_to resume_messages_path
    else
      render :show
    end
  end

  private
  def message_params
    params.require(:message).permit(:subject, :recipient, :body, :resume)
  end

  def set_resume
    @resume = Resume.find(params[:resume_id])
  end

  def set_message
    @message = Message.find(params[:id])
  end

  def record_not_found
    redirect_to messages_path
  end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :set_resume, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  def index
    @resumes = current_user.resumes
  end

  def show
  end

  def new
    @resume = Resume.new
  end

  def create
    @resume = current_user.resumes.new(resume_params)

    if @resume.save
      flash[:notice] = "Your resume was successfully uoloaded."
      redirect_to resumes_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @resume.assign_attributes(resume_params)

    if @resume.update_attributes(resume_params)
      flash[:notice] = "Your resume was successfully updated."
      redirect_to resume_path
    else
      render :edit
    end
  end

  def destroy
    if @resume.destroy
      flash[:notice] = "Your resume was deleted successfully."
      redirect_to resumes_path
    else
      render :show
    end
  end

  private
  def resume_params
    params.require(:resume).permit(:name, :document)
  end

  def set_resume
    @resume = Resume.find(params[:id])
  end

  def record_not_found
    redirect_to resumes_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @messages = current_user.messages
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(content)
  renderer = Redcarpet::Render::HTML.new()
  extensions = {
    hard_wrap: true, filter_html: true
  }

    Redcarpet::Markdown.new(renderer).render(content).html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="content-div title">
  <h1 class="heading heading-text">Resume Box</h1>
  <p class="description">A web app for managing versions of your resume and sharing them with others</p>
  <%= image_tag("resumes-graphic.png", class: "resumes-graphic") %>
</div>
<div class="content-div manage">
  <h1 class="heading">Manage Multiple</br>Resume Versions</h1>
  <p class="description">Back-end Developer Resume &#10003;</p>
  <p class="description">Rails Developer Resume &#10003;</p>
  <%= image_tag("mail-graphic.png", class: "mail-graphic") %>
</div>
<div class="content-div share">
  <h1 class="heading">Share</br>Your Resume</h1>
  <p class="description">And personalize your approach with a tailored message</p>
  <p class="description quote">"I thought you might like to see my resume!"</p>
  <%= link_to "Sign Up Today!", new_user_registration_path, class: 'btn btn-success btn-lg custom' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Resume Box</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

    <ul class="nav nav-tabs">
      <% if user_signed_in? %>
        <li class="dropdown pull-right user-signed-in-padding-right">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#"><strong><%= current_user.email %></strong>
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
        <li class="pull-right"><%= link_to 'Messages', messages_path %></li>
        <li class="pull-right"><%= link_to 'Resumes', resumes_path %></li>
      <% else %>
        <li class="pull-right"><%= link_to "Sign In", new_user_session_path %></li>
        <li class="pull-right"><%= link_to "Sign Up", new_user_registration_path %></li>
      <% end %>
    </ul>

    <% if user_signed_in? %>
      <div class="flash">
        <% if flash[:notice] %>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:notice] %>
          </div>
        <% elsif flash[:alert] %>
          <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:alert] %>
          </div>
        <% end %>
      </div>
    <% end %>

    <%= yield %>

</body>
</html>

app/views/messages/index.html.erb
<div class="container">
  <h1>Messages</h1>
  <br>
  <% @messages.each do |message| %>
    <hr>
    <h4><%= message.subject %></h4>
    <p><strong>To: </strong><%= message.recipient %></p>
    <p><strong>Sent: </strong>
      <% if message.created_at > Time.now.beginning_of_day %>
        <%= "#{time_ago_in_words(message.created_at)} ago" %>
      <% else %>
        <%= "on #{message.created_at.strftime("%b %d, %Y")}" %>
      <% end %>
    </p>
    <p><strong>Attatched Resume: </strong><%= message.resume.name %></p>
    <%= link_to 'View Message', resume_message_path(message.resume, message), class: 'button large' %>
    <br>
    <br>
  <% end %>
</div>
<br>

app/views/messages/new.html.erb
<div class="container">
  <% if @message.errors.any? %>
    <div class="flash alert alert-warning">
      <h4><%= pluralize(@message.errors.count, "Error") %>:</h4>
      <ul>
        <% @message.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <h1>New Message</h1>
  <br>
  <hr>
  <div class="container">
    <%= form_for [@resume, @message] do |f| %>
      <div class="row">
        <p><strong>Recipient</strong></p>
        <%= f.text_field :recipient, class: 'border col-md-3 col-sm-4 col-xs-8' %>
      </div>
      <div class="row">
        <p><strong>Subject</strong></p>
        <%= f.text_field :subject, class: 'border col-md-3 col-sm-4 col-xs-8' %>
      </div>
      <div class="row">
        <p><strong>Message</strong></p>
        <%= f.text_area :body, size: "45x10", class: 'border text-area' %>
      </div>
      <br>
      <div class="row">
        <p class="note">The following text and link will be placed beneath your message:</p>
        <p class="note">"Please click <%= link_to "here", "#{@resume.document}", target: ':_blank' %> to view my resume."</p>
      </div>
      <div class="row">
        <%= f.submit "Send", class: 'button send' %>
      </div>
    <% end %>
  </div>
</div>
<br>

app/views/messages/show.html.erb
<div class="container">
  <h1><%= @message.subject %></h1>
  <br>
  <hr>
  <p><strong>To: </strong><%= @message.recipient %></p>
  <p><strong>Sent: </strong>
    <% if @message.created_at > Time.now.beginning_of_day %>
      <%= "#{time_ago_in_words(@message.created_at)} ago" %>
    <% else %>
      <%= "on #{@message.created_at.strftime("%b %d, %Y")}" %>
    <% end %>
  </p>
  <p><strong>Attatched Resume: </strong><%= @message.resume.name %></p>
  <div class="parent">
    <div class="child-one">
      <p class="body"><strong>Body: </strong></p>
    </div>
    <div class="child-two">
      <p><%= markdown @message.body %></p>
      <p>Please click <%= link_to "here", "#{@message.resume.document}", target: ':_blank' %> to view my resume.</p>
    </div>
  </div>
  <hr>
  <%= link_to 'Delete', [@message.resume, @message], method: :delete, class: 'button delete', data: { confirm: 'Are you sure you want to delete this message? It will still appear in your inbox. Whomever you sent it to will still have it as well.' } %>
</div>

app/views/resumes/_form.html.erb
<br>
<div class="container">
  <div class="row">
    <h4 class="field-name">Resume Name</h4>
  </div>
  <%= form_for(@resume, multipart: true) do |f| %>
    <div class="row">
      <%= f.text_field :name, class: 'col-md-4 col-xs-12', placeholder: "Enter a name for your resume" %>
    </div>
    <br>
    <div class="row">
      <%= f.file_field :document %>
    </div>
    <br>
    <div class="row">
      <%= f.submit "Save", class: 'button save' %>
    </div>
<% end %>
</div>

app/views/resumes/edit.html.erb
<div class="container">
  <h1>Edit Resume</h1>
  <br>
  <hr>
  <div class="container">
    <div class="row">
      <p><strong>Resume Name: </strong><%= @resume.name %></p>
      <p><strong>Attached File: </strong><%= @resume.document_file_name %></p>
    </div>
    <br>
    <%= form_for(@resume, multipart: true) do |f| %>
      <div class="row">
        <p><strong>Edit Resume Name</strong></p>
        <%= f.text_field :name, class: 'border col-md-3 col-sm-4 col-xs-8' %>
      </div>
      <br>
      <div class="row">
        <p><strong>Replace Attached File</strong></p>
        <%= f.file_field :document %>
      </div>
      <br>
      <div class="row">
        <%= f.submit "Save", class: 'button' %>
      </div>
    <% end %>
  </div>
</div>

app/views/resumes/index.html.erb
<div class="container">
  <h1>Resumes</h1>
  <%= link_to "New Resume", new_resume_path, class: 'button large' %>
  <br>
  <% @resumes.each do |resume| %>
    <hr>
    <h3><%= resume.name %></h3>
    <%= link_to "View", "#{resume.document}", target: ':_blank', class: 'button' %>
    <%= link_to "Details", resume_path(resume), class: 'button' %>
    <%= link_to "Send", new_resume_message_path(resume), class: 'button' %>
    <br>
    <br>
  <% end %>
  <br>
</div>
<br>

app/views/resumes/new.html.erb
<div class="container">
  <% if @resume.errors.any? %>
    <div class="flash alert alert-warning">
      <h4><%= pluralize(@resume.errors.count, "Error") %>:</h4>
      <ul>
        <% @resume.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <h1>New Resume</h1>
  <br>
  <hr>
  <div class="container">
    <%= form_for(@resume, multipart: true) do |f| %>
      <div class="row">
        <p><strong>Resume Name</strong></p>
        <%= f.text_field :name, class: 'border col-md-3 col-sm-4 col-xs-8', placeholder: "Enter a name for your resume" %>
      </div>
      <br>
      <div class="row">
        <p><strong>Attached File</strong></p>
        <p>(Only .pdf, .doc, and .docx files are supported.)</p>
        <%= f.file_field :document %>
      </div>
      <br>
      <div class="row">
        <%= f.submit "Save", class: 'button' %>
      </div>
    <% end %>
  </div>
</div>

app/views/resumes/show.html.erb
<div class="container">
  <h1><%= @resume.name %></h1>
  <br>
  <hr>
  <p><strong>Attached File: </strong><%= @resume.document_file_name %></p>
  <p><strong>File Size: </strong><%= number_to_human_size(@resume.document_file_size) %></p>
  <p class="resume-show-bottom-p-padding-bottom"><strong>Last Modified: </strong>
    <% if @resume.updated_at > Time.now.beginning_of_day %>
      <%= "#{time_ago_in_words(@resume.updated_at)} ago" %>
    <% else %>
      <%= "on #{@resume.updated_at.strftime("%b %d, %Y")}" %>
    <% end %>
  </p>
  <hr>
    <%= link_to "View", "#{@resume.document}", target: ':_blank', class: 'button' %>
    <%= link_to "Edit", edit_resume_path(@resume), class: 'button' %>
    <%= link_to "Delete", @resume, method: :delete, class: 'button', data: { confirm: 'Are you sure you want to delete this resume?' } %>
</div>

app/views/share_resume/share_resume_email.html.erb
<h1>Test Email</h1>

app/views/users/show.html.erb
<div class="container">
  <h1>Sent Messages</h1>
  <%= link_to 'Back', resumes_path, class: 'button delete' %>
  <br>
  <% @messages.each do |message| %>
    <hr>
    <h4><%= message.subject %></h4>
    <p><strong>To: </strong><%= message.recipient %></p>
    <p><strong>Sent: </strong>
      <% if message.created_at > Time.now.beginning_of_day %>
        <%= "#{time_ago_in_words(message.created_at)} ago" %>
      <% else %>
        <%= "on #{message.created_at.strftime("%b %d, %Y")}" %>
      <% end %>
    </p>
    <p><strong>Resume: </strong><%= message.resume %></p>
  <% end %>
</div>